### ISSUE TITLE
attach and validate token

### ISSUE THREAD

**Issue by gyozob** [VD39/a-mean-stack-recipe-keeper#3]
Hi, the token from the localstorage isn't attached to each api request (e.g put it in the request header) made from the angular service. Also the generated token returned in AuthenticationRoute->login isn't validated on each request. jsonwebtoken package has a verify method, that should be used in a middleware to validate the received token from the request in order to deny requests coming with no token, expired, malformed or bad token  (api security reason - for real life apis this is crucial otherwise anybody could call your api routes - with postman for e.g - without being authenticated). This is just a friendly notice, it's up to if you want to make those changes or not :)

**Comment by VD39** [comment]
These changes are currently being made, however as this is just really a side project, it might take some time before I finish implementing. Thank you anyway, much appreciated. :)
